initial mypy support
pyslackers/slack-sansio pull request #43
Opened 2018-08-23 06:48 UTC by autoferrit

For now, just silencing a few items im not sure how to type properly yet, and doing some basic typings in actions.py. also adding it so it can be run in travis

2018-08-23 11:24 UTC, ovv requested changes
Looks pretty straightforward :+1:

2018-08-23 11:24 UTC, ovv commented on .travis.yml
> +  - pipenv run mypy slack/
Could you add that into the `slack/tests/test.sh` script instead

2018-08-23 11:24 UTC, ovv commented on slack/actions.py
> +    def dispatch(self, action: Dict[str, Any]):
action should be of type `Action` of the same file (same for the other method :point_down: )

2018-08-23 11:24 UTC, ovv commented on slack/tests/conftest.py
> +@pytest.fixture(params={**data.Events.__members__, **data.Messages.__members__}) # type: ignore
I guess these are some weird cases ? If you have any idea for improving all that feel free to share :)

2018-08-23 17:19 UTC, autoferrit commented on slack/tests/conftest.py
> +@pytest.fixture(params={**data.Events.__members__, **data.Messages.__members__}) # type: ignore
Yea these im not sure yet. but im just silencing them for now until i do some more typing and get a better idea when I should put here if anything. When I get home, ill paste the error mypy is showing to see if you have an idea.

2018-08-24 05:39 UTC, autoferrit commented
Last build on 3.6 simply errored out. last fix im hoping fixed the issue. can it just be restarted?

2018-08-24 06:39 UTC, ovv commented
restarted but it fails on dist build

2018-08-24 10:58 UTC, ovv commented
It should work if you rebase on master. I disabled check for non 3.7 version

2018-08-24 17:45 UTC, autoferrit commented
Woohoo. works now. I squashed the commits as well when I was rebasing.

2018-08-24 18:53 UTC, ovv approved these changes

2018-08-24 18:55 UTC, merged